# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SiyaRam' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'FirebaseCore'
pod 'FirebaseFirestore'
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseDatabase'
pod 'FirebaseCrashlytics'
pod 'Firebase'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseStorage'
pod 'Kingfisher'
end
